name: Build and Deploy Pages

on:
  push:
    branches: [ "master" ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: | 
        sudo apt-get update
        sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-latex-extra pandoc 
    
    - name: Build Site
      run: make

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload site
      uses: actions/upload-pages-artifact@v3
      with:
        path: '_site'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
