name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install
      uses: pandoc/actions/setup@{main}
      with:
        version: 2.19
    
    - name: Build Site
      run: make
